name: Android Release

on:
  release:
    types: [published]

  workflow_dispatch:

# In part from https://blog.logrocket.com/flutter-ci-cd-using-github-actions/
jobs:
  deploy:
    name: Build Android app and release to Internal Play Store track
    runs-on: ubuntu-latest
    environment: Android Beta
    steps:
      - uses: actions/checkout@v3

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.PLAY_STORE_KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.PLAY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.PLAY_STORE_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.PLAY_STORE_KEY_ALIAS }}" >> android/key.properties

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Start Android Release Build
        run: flutter build appbundle

      - name: Release Build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_KEY_JSON }}
          packageName: com.uclapi.uclassistant
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: beta
          status: completed
